### ISSUE TITLE
上传视频报错

### ISSUE THREAD

**Issue by dfaofeng** [Aruelius/acfun_upload#1]
~~~
Traceback (most recent call last):
  File "ac.py", line 4, in <module>
    acfun.create_douga(
  File "C:\Users\刀锋\AppData\Local\Programs\Python\Python38\lib\site-packages\acfun_upload\acfun.py", line 170, in create_douga
    add()
  File "C:\Users\刀锋\AppData\Local\Programs\Python\Python38\lib\site-packages\acfun_upload\acfun.py", line 150, in add
    "coverUrl": self.cover(cover),
  File "C:\Users\刀锋\AppData\Local\Programs\Python\Python38\lib\site-packages\acfun_upload\acfun.py", line 195, in cover
    "token": get_qiniu_token()
  File "C:\Users\刀锋\AppData\Local\Programs\Python\Python38\lib\site-packages\acfun_upload\acfun.py", line 184, in get_qiniu_token
    r.json()["vdata"]["uptoken"]
KeyError: 'vdata'
~~~
上传到分块87报错

**Comment by Aruelius** [comment]
重新上传呢。

**Comment by dfaofeng** [comment]
> 重新上传呢。

好像是最后封面上传失败,视频分块都传完了

**Comment by Aruelius** [comment]
对，等我有空看看，可能是接口改了，或者什么的。

**Comment by dfaofeng** [comment]
> 对，等我有空看看，可能是接口改了，或者什么的。

我先调试下看看.看能不能解决问题

**Comment by Aruelius** [comment]
修改好了欢迎PR，哈哈哈。

**Comment by dfaofeng** [comment]
> 修改好了欢迎PR，哈哈哈。

你这个登录方法能不能单独把token拿出来阿.每次登录很容易触发风控...找到问题了。。。你uptoken写错了.应该是upToken

**Comment by Aruelius** [comment]
可以把 Cookies 保存下来，不过 A 站每次正常登录都不需要验证码，无所谓了。

**Comment by dfaofeng** [comment]
pull了 同意吧.这个只是能用.剩下的多线程上传.多p上传也得做了

**Comment by Aruelius** [comment]
懒得做了，坐等大佬们PR。
https://github.com/Aruelius/bilibili_upload 批站这个是多线程。
至于多P，这个确实懒得做。。

**Comment by dfaofeng** [comment]
> 懒得做了，坐等大佬们PR。
> https://github.com/Aruelius/bilibili_upload 批站这个是多线程。
> 至于多P，这个确实懒得做。。

b站的早就有人做了.现在就是做a站的
